[{
    "id": 1,
    "claim_id": 3557147,
    "not_quote": false,
    "delivery_time": null,
    "original_parts": null,
    "spare_tire_amount": 0.0,
    "brand": "FORD",
    "tire_model": "CONTI POWER CONTACT",
    "llanta_type": "LLANTA DE CHAPA",
    "tire_width": 65,
    "tire_height": 175,
    "tire_tread": 14,
    "obs": "Detalle de la Compañía: Cubierta CONTINENTAL 175/65/14\r\nLlanta 0",
    "tire_quoted": null,
    "daytona_ids": null,
    "quote_state": null,
    "tenders": {
        "id": 1,
        "claim_id": 3557147,
        "claim_date": "2024-05-28",
        "name": "ANOBILE, JUAN CRUZ",
        "claim_number": "3557147",
        "phone": "-",
        "vehicle": "GOL 1.6 MI 5 P. DUBLIN",
        "domain": "DSQ-387",
        "type": "Ruedas",
        "company": "LA EQUITATIVA",
        "company_id": 19,
        "claim_state": "N",
        "has_image": "N",
        "brand": "FORD",
        "model": null,
        "chasis": "9BFZH55K1J8049501",
        "vehicle_year": 2017,
        "province": "CAPITAL FEDERAL",
        "city": "CIUDAD AUTONOMA DE BUENOS AIRES",
        "not_quote": false,
        "delivery_time": null,
        "original_parts": null,
        "spare_tire_obs": "Detalle de la Compañía: Cubierta CONTINENTAL 175/65/14\r\nLlanta 0",
        "timestamps": "2024-05-28T15:01:20.439271Z"
    },
},]