export const formFields = [
  {
    section: 'Encabezado',
    fields: [
      {
        label: 'Requerido / Comercial',
        field: 'comerciales',
        type: 'api-select',
        span: 8,
        required: true,
        mode: 'multiple',
        endpoint: 'users',
        valueField: 'id',
        nameField: 'username',
      },
      {
        label: 'Cliente Final',
        field: 'client_id',
        type: 'api-select',
        span: 8,
        required: true,
        mode: 'single',
        endpoint: 'clients/',
        valueField: 'id',
        nameField: 'name',
      },
      {
        label: 'Cliente Secundario',
        field: 'second_client_id',
        type: 'api-select',
        span: 8,
        required: true,
        mode: 'single',
        endpoint: 'clients/',
        valueField: 'id',
        nameField: 'name',
      },
      // {
      //   label: 'Posiciones a cubrir',
      //   field: 'hiring_positions_id',
      //   type: 'api-select',
      //   span: 8,
      //   required: true,
      //   mode: 'multiple',
      //   endpoint: 'hiring-positions/',
      //   valueField: 'id',
      //   nameField: 'name',
      // },
      {
        label: 'Perfil Primario',
        field: 'profile',
        type: 'api-select',
        span: 8,
        required: true,
        endpoint: 'primary-profiles/',
        valueField: 'id',
        nameField: 'name',
      },
      {
        label: 'Perfil Secundario',
        field: 'subprofile',
        type: 'api-select',
        span: 8,
        endpoint: 'sub-profiles/',
        valueField: 'id',
        nameField: 'name',
        dependsOn: 'profile',
        dependsParam: 'primary_profile',
      },
      {
        label: 'Seniority',
        field: 'seniority',
        type: 'api-select',
        mode: 'multiple',
        span: 8,
        endpoint: 'seniority-levels/',
        valueField: 'id',
        nameField: 'name',
      },
      {
        label: 'Código Accenture',
        field: 'code',
        type: 'input',
        span: 8,
        required: (data) => data.client && data.client.name === 'Accenture',
      },
      {
        label: 'Fecha de creación',
        field: 'opening_date',
        type: 'input',
        span: 8,
        disabled: true,
      },
    ],
  },
  {
    section: 'Descripción de Tareas',
    fields: [
      {
        label: 'Descripción de Tareas',
        field: 'task_description',
        type: 'textarea',
        span: 24,
        required: true,
        placeholder: 'Copia y pega aquí la descripción (HTML soportado)',
      },
    ],
  },
  {
    section: 'Requerimientos Técnicos',
    fields: [
      {
        label: 'Requerimientos Técnicos (200-400 caracteres)',
        field: 'tech_requirements',
        type: 'textarea',
        span: 24,
        required: true,
      },
      {
        label: 'Skills Excluyentes',
        field: 'skills',
        type: 'tags',
        span: 24,
        required: true,
        placeholder: 'Añade skills como Java, Python, etc. y presiona Enter',
      },
    ],
  },
  {
    section: 'Requisito Soft',
    fields: [
      {
        label: 'Requisito soft (opcional, recomendado)',
        field: 'soft_requirements',
        type: 'textarea',
        span: 24,
      },
      {
        label: 'Competencias Soft',
        field: 'soft_skills',
        type: 'tags',
        span: 24,
        placeholder: 'Comunicación, autonomía, etc.',
      },
    ],
  },
];
