export const cards = [
    {
        claim_id: "3788052",
        vehicle: 'ECO SPORT 1.6 TITANIUM        L/13',
        domain: 'MWY-226',
        description: "Descripción de licitación 1",
        company_name: 'LA SEGUNDA',
        quote_state: 'N',
        claim_date: '2024-11-05',
        city: 'Berazategui',
        province: 'BUENOS AIRES',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjxbT6ppO1lPLNKZneXzb_A78LMY3YuCC5_w&s",
    },
    {
        claim_id: "3784248",
        vehicle: 'CRUZE 1.4 4 PTAS LTZ  AT',
        domain: 'AF131QB',
        company_name: 'SAN CRISTOBAL',
        quote_state: 'N',
        claim_date: '2024-11-02',
        city: 'VILLA ELISA',
        province: 'BUENOS AIRES',
        description: "Descripción de licitación 2",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWR0Of9YGh0OZuYYdzzuBmvCYC5R9i1dfwBw&s",
    },
    {
        claim_id: "3804882",
        vehicle: 'AMAROK 20TD 4X2 DC COM 180HP   L17',
        domain: 'AG191DI',
        company_name: 'FEDERACION PATRONAL',
        quote_state: 'A',
        claim_date: '2024-11-13',
        city: 'CIUDAD AUTONOMA DE BUENOS AIRES',
        province: 'CAPITAL FEDERAL',
        description: "Sin imagen para esta tarjeta",
    },
    {
        claim_id: "3783346",
        vehicle: 'PALIO 1.6 5 P ESSENCE  L/14',
        domain: 'POV-111',
        company_name: 'FEDERACION PATRONAL',
        quote_state: 'E',
        claim_date: '2024-11-01',
        city: 'SALTO',
        province: 'BUENOS AIRES',
        description: "Tarjeta personalizada",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsVeMyBQwVsc0FjRiSHzT7PPqp_iafAI6KCw&s",
        // cardStyle: { backgroundColor: "#e0f7fa" },
    },
    {
        claim_id: "3801743",
        vehicle: 'RANGER 2.2 TDI SC 4X2 L/18 XL SAF',
        domain: 'AC004BU',
        company_name: 'FEDERACION PATRONAL',
        quote_state: 'LO',
        claim_date: '2024-11-11',
        city: 'QUILMES OESTE',
        province: 'BUENOS AIRES',
        description: "Hover deshabilitado",
        hoverable: false,
    },
    {
        claim_id: "3781341",
        vehicle: 'FOCUS L/14 2.0 4 P SE PLUS AUT',
        domain: 'OEG-626',
        company_name: 'FEDERACION PATRONAL',
        quote_state: 'A',
        claim_date: '2024-10-31',
        city: 'NEUQUEN',
        province: 'NEUQUÉN',
        description: "Otra tarjeta",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKmqEroWzOfU7L6pUdwtV0lt1sL1I1p_5gWg&s'
    },
];